name: DawFaction
version: '${project.version}'
main: com.daweii.dawfaction.Main
api-version: 1.15
authors: [ Daweii ]
description: Factions Plugins
commands:
  vanish:
    description: rendre invisible un joueur (staff)
  sethome:
    description: cree un home
  home:
    description: TP a un home
